@startjson
' <style>
' jsonDiagram {
'   node {
'     BackGroundColor Khaki
'     LineColor lightblue
'     FontName Helvetica
'     FontColor red
'     FontSize 18
'     FontStyle bold
'     RoundCorner 0
'     LineThickness 2
'     LineStyle 10;5
'     separator {
'       LineThickness 0.5
'       LineColor black
'       LineStyle 1;5
'     }
'   }
'   arrow {
'     BackGroundColor lightblue
'     LineColor green
'     LineThickness 2
'     LineStyle 2;5
'   }
'   highlight {
'     BackGroundColor red
'     FontColor white
'     FontStyle italic
'   }
' }
' </style>
#highlight "imports"
#highlight "imports" / "0" / "code" 
#highlight "exports"
' #highlight "address" / "city"
' #highlight "phoneNumbers" / "0" / "number"
{
	"imports": [{
			"code": "china_stat",
			"reports": [
				"exporter",
				"hs_code",
				"origin_country_code",
				"country_of_destination",
				"product_desc",
				"merchant",
				"..."
			],
			"statFields": [
				"importer,importer.raw:1",
				"exporter,exporter.raw:1",
				"weight,weight:0",
				"quantity,qty:0",
				"sumOfMoney,sumOfUSD:0",
				"teus,teu:0",
				"..."
			],
			"lang": [
				"en",
				"cn",
				"..."
			]
		},
		{
			"code": "russia",
			"reports": [
				"exporter",
				"hs_code",
				"origin_country_code",
				"country_of_destination",
				"product_desc",
				"merchant",
				"..."
			],
			"statFields": [
				"importer,importer.raw:1",
				"exporter,exporter.raw:1",
				"weight,weight:0",
				"quantity,qty:0",
				"sumOfMoney,sumOfUSD:0",
				"teus,teu:0",
				"..."
			],
			"lang": [
				"en",
				"ru",
				"..."
			]
		},
		{
			"code": "...",
			"reports": ["..."],
			"statFields": ["..."],
			"lang": ["..."]
		}
	],
	"exports": [{
		"code": "...",
		"reports": ["..."],
		"statFields": ["..."],
		"lang": ["..."]
	}]
}
@endjson