@startjson
#highlight "imports"
#highlight "imports" / "0" / "dsCode"
#highlight "imports" / "1" / "dsCode"
#highlight "imports" / "2" / "dsCode"
#highlight "exports"
#highlight "exports" / "0" / "dsCode" 
#highlight "exports" / "1" / "dsCode" 
' #highlight "address" / "city"
' #highlight "phoneNumbers" / "0" / "number"
{
   "imports":[
      {
         "dsCode":"china_stat",
         "config":[
            {
               "fieldCategory":"COMPANY_IMPORTER",
               "config":[
                  {
                     "source":"jksmc",
                     "seq":1,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"进口商名称",
                     "en":"importer name"
                  },
                  {
                     "source":"jksdz",
                     "seq":2,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"进口商地址",
                     "en":"importer address"
                  },
                  {
                     "source":"jksdm",
                     "seq":3,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"...",
                     "en":"..."
                  },
                  {
                     "source":"lxfslx",
                     "seq":5,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"...",
                     "en":"..."
                  },
                  {
                     "source":"lxfs",
                     "seq":6,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"...",
                     "en":"..."
                  }
               ]
            },
            {
               "fieldCategory":"COMPANY_EXPORTER",
               "config":[
                  {
                     "source":"cksmc",
                     "seq":1,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"...",
                     "en":"..."
                  },
                  {
                     "source":"...",
                     "seq":2,
                     "fieldType":"...",
                     "displayType":"...",
                     "cn":"...",
                     "en":"..."
                  }
               ]
            },
            {
               "fieldCategory":"COMPANY_NOTIFIER",
               "config":[
                  {
                     "source":"tzrmc",
                     "seq":1,
                     "fieldType":"str",
                     "displayType":"x",
                     "cn":"...",
                     "en":"..."
                  },
                  {
                     "source":"...",
                     "seq":2,
                     "fieldType":"...",
                     "displayType":"...",
                     "cn":"...",
                     "en":"..."
                  }
               ]
            },
            {
               "fieldCategory":"SHIPPING",
               "config":[
                  {
                     "source":"...",
                     "seq":"...",
                     "fieldType":"...",
                     "displayType":"..."
                  }
               ]
            },
            {
               "fieldCategory":"CONTAINER",
               "config":[
                  {
                     "source":"...",
                     "seq":"...",
                     "fieldType":"...",
                     "displayType":"..."
                  }
               ]
            },
            {
               "fieldCategory":"PRODUCT",
               "config":[
                  {
                     "source":"...",
                     "seq":"...",
                     "fieldType":"...",
                     "displayType":"..."
                  }
               ]
            },
            {
               "fieldCategory":"DESCRIPTION",
               "config":[
                  {
                     "source":"...",
                     "seq":"...",
                     "fieldType":"...",
                     "displayType":"..."
                  }
               ]
            },
            {
               "fieldCategory":"HAZARDOUS",
               "config":[
                  {
                     "source":"...",
                     "seq":"...",
                     "fieldType":"...",
                     "displayType":"..."
                  }
               ]
            }
         ]
      },
      {
         "dsCode":"russia",
         "config":[
            "..."
         ]
      }
   ],
   "exports":[
      {
         "dsCode":"china_stat",
         "config":[
            "..."
         ]
      }
   ]
}
@endjson