@startjson
#highlight "imports"
#highlight "imports" / "0" / "dsCode"
#highlight "imports" / "1" / "dsCode"
#highlight "imports" / "2" / "dsCode"
#highlight "exports"
#highlight "exports" / "0" / "dsCode" 
#highlight "exports" / "1" / "dsCode" 
' #highlight "address" / "city"
' #highlight "phoneNumbers" / "0" / "number"
{
    "imports": [
        {
            "dsCode": "china_stat",
            "config": [
                {
                    "fieldType": "COMPANY",
                    "config": [
                        {
                            "subType": "IMPORTER",
                            "config": [
                                {
                                    "source": "jksmc",
                                    "seq": 1,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "jksdz",
                                    "seq": 2,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "jksdm",
                                    "seq": 3,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "lxfslx",
                                    "seq": 5,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "lxfs",
                                    "seq": 6,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                }
                            ]
                        },
                        {
                            "subType": "EXPORTER",
                            "config": [
                                {
                                    "source": "cksmc",
                                    "seq": 1,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "...",
                                    "seq": 2,
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        },
                        {
                            "subType": "NOTIFIER",
                            "config": [
                                {
                                    "source": "tzrmc",
                                    "seq": 1,
                                    "default": "",
                                    "dataType": "str",
                                    "alias": "",
                                    "displayType": "x"
                                },
                                {
                                    "source": "...",
                                    "seq": 2,
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                },
                {
                    "fieldType": "SHIPPING",
                    "config": [
                        {
                            "subType": "",
                            "config": [
                                {
                                    "source": "...",
                                    "seq": "...",
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                },
                {
                    "fieldType": "CONTAINER",
                    "config": [
                        {
                            "subType": "",
                            "config": [
                                {
                                    "source": "...",
                                    "seq": "...",
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                },
                {
                    "fieldType": "PRODUCT",
                    "config": [
                        {
                            "subType": "",
                            "config": [
                                {
                                    "source": "...",
                                    "seq": "...",
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                },
                {
                    "fieldType": "DESCRIPTION",
                    "config": [
                        {
                            "subType": "",
                            "config": [
                                {
                                    "source": "...",
                                    "seq": "...",
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                },
                {
                    "fieldType": "HAZARDOUS",
                    "config": [
                        {
                            "subType": "",
                            "config": [
                                {
                                    "source": "...",
                                    "seq": "...",
                                    "default": "...",
                                    "dataType": "...",
                                    "alias": "...",
                                    "displayType": "..."
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "dsCode": "russia",
            "config": [
                "..."
            ]
        }
    ],
    "exports": [
        {
            "dsCode": "china_stat",
            "config": ["..."]
        }
    ]
}
@endjson